name: Build WebAppDocker Image

on:
  push:
    branches: [ main ]
    paths:
      - "src/WebApp/**"
  pull_request:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t webapp-image -f src/WebApp/Dockerfile .

      - name: Run container test
        run: |
          docker run -d -p 8080:80 --name webapp-test webapp-image
          sleep 10
          curl -f http://localhost:8080/ || exit 1
          docker stop webapp-test
    
